export interface AIService {
    summarize(text: string): Promise<string>;
    generateQuiz(text: string): Promise<Quiz>;
    chat(messages: ChatMessage[], context: string): Promise<string>;
}

export interface Quiz {
    title: string;
    questions: QuizQuestion[];
}

export interface QuizQuestion {
    id: string;
    question: string;
    options: string[];
    correctAnswer: number; // Index of correct option
}

export interface ChatMessage {
    role: 'user' | 'assistant' | 'system';
    content: string;
}

const MOCK_DELAY = 1500;

export const MockAIService: AIService = {
    summarize: async (text: string) => {
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve(
                    `## Summary\n\nThis is a generated summary of your note. based on the content:\n\n> "${text.substring(0, 50)}..."\n\n* Key point 1: The note discusses important concepts.\n* Key point 2: Several details were noted about the subject.\n* Key point 3: Further research is recommended.\n\n_Generated by AI_`
                );
            }, MOCK_DELAY);
        });
    },

    generateQuiz: async (text: string) => {
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    title: "Knowledge Check",
                    questions: [
                        {
                            id: "1",
                            question: "What is the primary focus of this note?",
                            options: ["React Development", "AI Integration", "Cooking Recipes", "Space Travel"],
                            correctAnswer: 1
                        },
                        {
                            id: "2",
                            question: "Which hook is likely used for state management here?",
                            options: ["useEffect", "useState", "useReducer", "useCallback"],
                            correctAnswer: 1
                        },
                        {
                            id: "3",
                            question: "True or False: The AI service is currently using real API keys.",
                            options: ["True", "False"],
                            correctAnswer: 1
                        }
                    ]
                });
            }, MOCK_DELAY);
        });
    },

    chat: async (messages: ChatMessage[], context: string) => {
        return new Promise((resolve) => {
            setTimeout(() => {
                const lastUserMessage = messages[messages.length - 1].content;
                resolve(
                    `I understand you're asking about "${lastUserMessage}". \n\nGiven the context of your note (length: ${context.length} chars), I can suggest that you focus on structuring your data primarily. Is there anything specific code block you'd like me to refactor?`
                );
            }, MOCK_DELAY);
        });
    }
};
